# Generated by Django 5.0.14 on 2026-04-03 06:40

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0093_uploadedfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorklogEntryPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('log_date', models.DateField(verbose_name='日志日期')),
                ('log_time', models.TimeField(blank=True, null=True, verbose_name='日志时间')),
                ('log_type', models.CharField(choices=[('morning', '早报'), ('preopen', '盘前'), ('intraday', '盘中'), ('postclose', '盘后'), ('alert', '提醒')], default='intraday', max_length=20, verbose_name='日志类型')),
                ('title_note', models.CharField(blank=True, max_length=255, verbose_name='补充标题')),
                ('summary', models.TextField(blank=True, verbose_name='摘要')),
                ('body', wagtail.fields.RichTextField(blank=True, verbose_name='正文')),
                ('points_used', models.PositiveIntegerField(default=0, verbose_name='消耗积分')),
                ('is_actionable', models.BooleanField(default=False, verbose_name='是否有动作价值')),
                ('related_symbols', models.CharField(blank=True, help_text='例如 300394,002156', max_length=255, verbose_name='相关股票')),
            ],
            options={
                'ordering': ['-log_date', '-log_time', '-first_published_at'],
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='WorklogIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
