# Generated by Django 5.0.14 on 2026-04-05 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_watchlist_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='MinuteBar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=16, verbose_name='股票代码')),
                ('name', models.CharField(blank=True, max_length=64, verbose_name='股票名称')),
                ('trade_date', models.DateField(db_index=True, verbose_name='交易日期')),
                ('bar_time', models.TimeField(db_index=True, verbose_name='分钟时间')),
                ('open_price', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='开盘价')),
                ('high_price', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='最高价')),
                ('low_price', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='最低价')),
                ('close_price', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='收盘价')),
                ('volume', models.BigIntegerField(default=0, verbose_name='成交量')),
                ('amount', models.DecimalField(decimal_places=3, default=0, max_digits=20, verbose_name='成交额')),
                ('source', models.CharField(default='akshare', max_length=32, verbose_name='数据源')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'ordering': ['-trade_date', '-bar_time', 'symbol'],
            },
        ),
        migrations.AddConstraint(
            model_name='minutebar',
            constraint=models.UniqueConstraint(fields=('symbol', 'trade_date', 'bar_time'), name='unique_symbol_trade_date_bar_time'),
        ),
    ]
